### ISSUE TITLE
Thank you and question about creating a pip-installable package

### ISSUE THREAD

**Issue by eracle** [cazevedo/gspn-lib#2]
First of all, I want to thank you for creating this Generalized Stochastic Petri Nets library in Python. It's a valuable resource for those of us working with stochastic processes, and I appreciate the effort you've put into developing and sharing this project.

I noticed that you have a refactored version of the library in [this repository](https://github.com/cazevedo/gspn-framework), which also includes additional software. The current structure that repository makes it challenging to create a pip-installable package for the library. I was wondering if you have considered applying those changes to this repository, which would allow for a more streamlined installation process using pip.

Having a pip-installable package would make it much easier for users to include your library in their projects and help increase its adoption. If you're open to this idea, I would be happy to help with the process and contribute to the project where needed.

Once again, thank you for your work, and I'm looking forward to your thoughts on this suggestion.

Best regards

**Comment by cazevedo** [comment]
Hello @eracle! Thank you for your comments and constructive suggestion.
That is something I have on the roadmap for the lib, but I still didn't have to time to implement it.
In the meantime what I suggest is that you just run "pip install -e ." locally.

Please feel free to propose changes to the code by creating a pull request.

Best regards

**Comment by eracle** [comment]
I noticed that you have a refactored version of the library in [this repository](https://github.com/cazevedo/gspn-framework), which also includes additional software. I was wondering if you have considered applying those changes to this repository.
